name: Deployment
on: [push]
jobs:
  dire_bonjour:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2 # Récupère le contenu du dépôt correspondant au commit du workflow en cours
    - run: sudo apt-get update && sudo apt-get install -y make && sudo apt-get install -y asciidoctor
    - run: make all && export NETLIFY_AUTH_TOKEN=_Tj2QCdE5_vWW3PXb02hAF2zKXdGd8_dgofP3SvnhmM && NETLIFY_SITE_ID=4a587bb6-e3f6-4fdd-8b55-ed296c2c8df4
    - run: netlify deploy --prod --dir=./dist/